var graphicLocations = {
	"mascots": "/Volumes/Customization/Library/Graphics/Mascots/",
	"player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"basketball player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"baseball and softball player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"baseball and softball player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"basketball player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"basketball player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"football player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"football player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"lacrosse player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"lacrosse player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"soccer player names": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"soccer player numbers": "/Volumes/Customization/Library/Graphics/Sublimation_Name_Numbers/",
	"logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"spirit logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"baseball and softball logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"basketball logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"football logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"7 on 7 football logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"lacrosse logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"soccer logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"wrestling logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"track logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"pant logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"badge logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"hoodie sleeve logos": "/Volumes/Customization/Library/Graphics/Sublimation/",
	"ghosted mascots": "/Volumes/Customization/Library/Graphics/Mascots/_Ghosted Mascots/",
	"background graphics": "/Volumes/Customization/Library/Graphics/Backgrounds/"
}


