var graphicLocations = {
	"mascots": graphicsPath + "Mascots/",
	"player names": graphicsPath + "Sublimation_Name_Numbers/",
	"player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"basketball player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"baseball and softball player names": graphicsPath + "Sublimation_Name_Numbers/",
	"baseball and softball player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"basketball player names": graphicsPath + "Sublimation_Name_Numbers/",
	"basketball player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"football player names": graphicsPath + "Sublimation_Name_Numbers/",
	"football player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"lacrosse player names": graphicsPath + "Sublimation_Name_Numbers/",
	"lacrosse player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"soccer player names": graphicsPath + "Sublimation_Name_Numbers/",
	"soccer player numbers": graphicsPath + "Sublimation_Name_Numbers/",
	"logos": graphicsPath + "Sublimation/",
	"spirit logos": graphicsPath + "Sublimation/",
	"baseball and softball logos": graphicsPath + "Sublimation/",
	"basketball logos": graphicsPath + "Sublimation/",
	"football logos": graphicsPath + "Sublimation/",
	"7 on 7 football logos": graphicsPath + "Sublimation/",
	"lacrosse logos": graphicsPath + "Sublimation/",
	"soccer logos": graphicsPath + "Sublimation/",
	"wrestling logos": graphicsPath + "Sublimation/",
	"track logos": graphicsPath + "Sublimation/",
	"pant logos": graphicsPath + "Sublimation/",
	"badge logos": graphicsPath + "Sublimation/",
	"hoodie sleeve logos": graphicsPath + "Sublimation/",
	"ghosted mascots": graphicsPath + "Mascots/_Ghosted Mascots/",
	"background graphics": graphicsPath + "Backgrounds/"
}


